[programs.devnet]
myepicproject = "8nGuYmJjCbcsdueLd7AcuyMwMjvAoWVEQxLUymf6VfxN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/muharrem/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
